# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'additional_schools_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_additionalSchoolsDialog(object):
    def setupUi(self, additionalSchoolsDialog):
        additionalSchoolsDialog.setObjectName("additionalSchoolsDialog")
        additionalSchoolsDialog.resize(641, 300)
        self.label_cityLayer = QtWidgets.QLabel(additionalSchoolsDialog)
        self.label_cityLayer.setGeometry(QtCore.QRect(10, 0, 380, 20))
        self.label_cityLayer.setObjectName("label_cityLayer")
        self.comboBox_cityLayer = QtWidgets.QComboBox(additionalSchoolsDialog)
        self.comboBox_cityLayer.setGeometry(QtCore.QRect(10, 20, 380, 25))
        self.comboBox_cityLayer.setObjectName("comboBox_cityLayer")
        self.label_easLayer = QtWidgets.QLabel(additionalSchoolsDialog)
        self.label_easLayer.setGeometry(QtCore.QRect(10, 40, 380, 20))
        self.label_easLayer.setObjectName("label_easLayer")
        self.comboBox_easLayer = QtWidgets.QComboBox(additionalSchoolsDialog)
        self.comboBox_easLayer.setGeometry(QtCore.QRect(10, 60, 380, 25))
        self.comboBox_easLayer.setObjectName("comboBox_easLayer")
        self.label_schoolsLayer = QtWidgets.QLabel(additionalSchoolsDialog)
        self.label_schoolsLayer.setGeometry(QtCore.QRect(10, 80, 380, 20))
        self.label_schoolsLayer.setObjectName("label_schoolsLayer")
        self.comboBox_schoolsLayer = QtWidgets.QComboBox(additionalSchoolsDialog)
        self.comboBox_schoolsLayer.setGeometry(QtCore.QRect(10, 100, 380, 25))
        self.comboBox_schoolsLayer.setObjectName("comboBox_schoolsLayer")
        self.label_population = QtWidgets.QLabel(additionalSchoolsDialog)
        self.label_population.setGeometry(QtCore.QRect(10, 120, 380, 20))
        self.label_population.setObjectName("label_population")
        self.lineEdit_population = QtWidgets.QLineEdit(additionalSchoolsDialog)
        self.lineEdit_population.setGeometry(QtCore.QRect(10, 140, 380, 25))
        self.lineEdit_population.setObjectName("lineEdit_population")
        self.button_execute = QtWidgets.QPushButton(additionalSchoolsDialog)
        self.button_execute.setGeometry(QtCore.QRect(150, 180, 100, 30))
        self.button_execute.setObjectName("button_execute")

        self.retranslateUi(additionalSchoolsDialog)
        QtCore.QMetaObject.connectSlotsByName(additionalSchoolsDialog)

    def retranslateUi(self, additionalSchoolsDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label_cityLayer.setText(_translate("additionalSchoolsDialog", "City Layer"))
        self.label_easLayer.setText(_translate("additionalSchoolsDialog", "Eas Layer"))
        self.label_schoolsLayer.setText(_translate("additionalSchoolsDialog", "Schools Layer"))
        self.label_population.setText(_translate("additionalSchoolsDialog", "Population"))
        self.button_execute.setText(_translate("additionalSchoolsDialog", "Generate Map"))
